version: "3.0"

services:
    geth:
        image: ethereum/client-go:${GETH_VERSION}
        entrypoint: /bin/sh
        volumes:
            - ./geth-data:/root/.ethereum
            - ${GETH_ANCIENT_CHAINDATA_DIR}:/root/ancient-data
            - ./scripts:/root/scripts:ro
            - ./jwttoken:/root/jwttoken:ro
        ports:
            - 30303:30303/tcp
            - 30303:30303/udp
        expose:
            - 8551
        env_file: .env
        command: /root/scripts/start-geth.sh
        restart: on-failure
        stop_grace_period: 3m
