version: "3.0"

services:
    beacon_node:
        image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
        volumes:
            - ./lighthouse-data:/root/.lighthouse
            - ./scripts:/root/scripts:ro
            - ./jwttoken:/root/jwttoken:ro
        ports:
            - 5052:5052/tcp
            - 5053:5053/tcp
            - 5054:5054/tcp     # metrics endpoint
            - 9000:9000/tcp
            - 9000:9000/udp
        env_file: .env
        command: sh /root/scripts/start-beacon-node.sh
        restart: on-failure
        stop_grace_period: 3m
    validator_client:
        image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
        volumes:
            - ./lighthouse-data:/root/.lighthouse
            - ./scripts:/root/scripts:ro
            - ./validator_keys:/root/validator_keys:ro
        depends_on:
            - beacon_node
        ports:
            - 5064:5064/tcp     # metrics endpoint
        env_file: .env
        command: sh /root/scripts/start-validator-client.sh
        restart: on-failure
        stop_grace_period: 3m
    mev_boost:
        image: flashbots/mev-boost:latest
        expose:
          - 18550
        command: -addr 0.0.0.0:18550 -mainnet -relay-check -relays ${MEV_RELAYS}
        env_file: .env
        restart: on-failure
