network="mainnet"
sync-mode="X_CHECKPOINT"
data-path="/var/lib/besu"
data-storage-format="BONSAI"
engine-rpc-port=8551
engine-jwt-secret="/home/besu/jwttoken/jwtsecret.hex"
engine-host-allowlist=["*"]
Xplugin-rocksdb-high-spec-enabled=true
